build-contract:
	cd pre-condor && make build-contract
	cd post-condor && make build-contract

create-fixture:
	cd pre-condor && make create-fixture
	cd post-condor && make create-fixture

setup-test:
	cd pre-condor && make setup-test
	cd post-condor && make setup-test

test:
	cd pre-condor && make test
	cd post-condor && make test

clippy:
	cd pre-condor && make clippy
	cd post-condor && make clippy

check-lint:
	cd pre-condor && make check-lint
	cd post-condor && make check-lint

lint:
	cd pre-condor && make lint
	cd post-condor && make lint

clean:
	cd pre-condor && make clean
	cd post-condor && make clean
